# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unichat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Unichat
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'UnichatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Unichat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Unichat-tvOS

  target 'Unichat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
